#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
stage="$(basename "$(realpath "$0")")"

echo "NODEJS"

display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m>> $1\033[0m"
}
command_exists() {
    command -v "$1" >/dev/null 2>&1
}
# ============================================================
NVM_VERSION="v0.40.7"
# https://github.com/nvm-sh/nvm#install--update-script
display_header "Installing NVM and NODEJS ($NVM_VERSION)"
if ! command_exists nvm; then
    echo "Installing NVM ($NVM_VERSION)"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    echo "☑ NVM - $NVM_VERSION"
    echo "Installing NODE LTS"
    nvm install node
    echo "☑ NODE LTS"
fi

# ============================================================

[[ -n $(command -v nvm) ]] && echo "☑ nvm"

echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
echo "reboot system"
