#!/bin/bash
set -e
stage="$(basename "$(realpath "$0")")"

echo "$stage - Updating System"
display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m($stage)>> $1\033[0m"
}
display_header "Checking sudo access"
sudo -v
# ============================================================
display_header "UPDATE APT packages"
sudo apt-get update && sudo apt-get upgrade -y

display_header "basic utilities"
sudo apt install curl git wget vim tree -y

echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
