#!/usr/bin/env bash
set -e
stage="$(basename "$(realpath "$0")")"

echo "$stage - DATABASES"
display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m($stage)>> $1\033[0m"
}
display_header "Checking sudo access"
sudo -v

# ============================================================
display_header "POSTGRESQL"
sudo apt install postgresql postgresql-contrib -y
echo "☑ postgresql"

display_header "MYSQL"
sudo apt install mysql-server libmysqlclient-dev -y
echo "☑ mysql"

display_header "REDIS"
sudo apt install redis-server -y
echo "☑ redis"

# ============================================================

echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
