#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
stage="$(basename "$(realpath "$0")")"

echo "TOOLS"
display_header() {
  echo "=================================================="
  echo -e "\n\033[1;34m>> $1\033[0m"
}
command_exists() {
  command -v "$1" >/dev/null 2>&1
}
display_header "Checking sudo access"
sudo -v || exit 1

# ============================================================
display_header "bat"
VERSION="0.26.1"
DEB="bat_${VERSION}_amd64.deb"
URL="https://github.com/sharkdp/bat/releases/download/v${VERSION}/${DEB}"
# sharkdp/bat/releases/latest

if ! command_exists bat; then
  wget "$URL" &&
      sudo apt install "./$DEB" &&
      rm -f "./$DEB"
else
  echo "=> bat already installed"
fi

# ============================================================
display_header "fd"
VERSION="10.5.0"
DEB="fd_${VERSION}_amd64.deb"
URL="https://github.com/sharkdp/fd/releases/download/v${VERSION}/${DEB}"
# sharkdp/fd/releases/download/v10.5.0/fd_10.5.0_amd64.deb

if ! command_exists fd; then
  wget "$URL" &&
      sudo apt install "./$DEB" &&
      rm -f "./$DEB"
else
  echo "=> fd already installed"
fi