#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
stage="$(basename "$(realpath "$0")")"

echo "TOOLS"
display_header() {
  echo "=================================================="
  echo -e "\n\033[1;34m>> $1\033[0m"
}
command_exists() {
  command -v "$1" >/dev/null 2>&1
}
display_header "Checking sudo access"
sudo -v

# ============================================================
display_header "bat"
# https://github.com/sharkdp/bat/releases/latest
wget "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat_0.26.1_amd64.deb"
