#!/usr/bin/env bash
set -e
stage="$(basename "$(realpath "$0")")"

echo "$stage - TOOLS"
display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m($stage)>> $1\033[0m"
}
command_exists() {
    command -v "$1" >/dev/null 2>&1
}


# ============================================================
display_header "glow (go)"
go install charm.land/glow/v3@latest
# go install github.com/charmbracelet/glow@latest
echo "☑ glow"
# ============================================================


# ============================================================
echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
echo "restart terminal"
