#!/bin/bash
set -e
target="Ubuntu 24.04"
stage="$(basename "$(realpath "$0")")"

echo "$stage - $target - installing base packages"

display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m($stage)>> $1\033[0m"
}
command_exists() {
    command -v "$1" >/dev/null 2>&1
}
display_header "Checking sudo access"
sudo -v


# ============================================================
display_header "Updating snap (itself)"
sudo snap refresh

# ============================================================
display_header "Installing base utilities"
sudo apt install curl git wget tree -y

# ============================================================
display_header "Installing build tools"
sudo apt install -y make build-essential \
    libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev \
    llvm libncurses-dev \
    xz-utils tk-dev libffi-dev liblzma-dev -y

echo "☑ apt build"

# ============================================================
display_header "Installing Python packages"
sudo apt-get install python3-pip python3-venv python3-gpg \
  python3-dev python3-openssl python3-tk python3-wheel \
  python3-setuptools -y

echo "☑ apt python packages"

# ============================================================
display_header "Installing search and utility tools"
sudo apt install vim silversearcher-ag jq sqlite3 -y

# ============================================================
display_header "Installing system monitoring"
sudo apt install htop btop -y

# ============================================================
display_header "Installing document tools"
sudo apt install pandoc pdftk w3m -y

# ============================================================
display_header "Installing fzf (git clone)"
if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
    echo "☑ fzf"
fi

# ============================================================
display_header "Installing pipx"
sudo apt install pipx -y && pipx ensurepath 
echo "☑ pipx"

# ============================================================
echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
echo "restart terminal"
