#!/usr/bin/env bash
set -e
stage="$(basename "$(realpath "$0")")"

echo "$stage - TOOLS"
display_header() {
    echo "=================================================="
    echo -e "\n\033[1;34m($stage)>> $1\033[0m"
}
command_exists() {
    command -v "$1" >/dev/null 2>&1
}
# display_header "Checking sudo access"
# sudo -v

# ============================================================
display_header "bat (cargo)"
# download package: bat_x.xx_amd64.deb
# https://github.com/sharkdp/bat/releases/latest
# cargo install --locked bat
# cargo install fd-find
# echo "☑ bat"

display_header "fd (apt)"
sudo apt install fd-find
echo "☑ fd"

# ============================================================
display_header "glow (go)"
go install charm.land/glow/v3@latest
# go install github.com/charmbracelet/glow@latest
echo "☑ glow"
# ============================================================


# ============================================================
echo "✅ $stage"
echo "✅ $stage - $(date '+%Y-%m-%d %H:%M:%S')" >> log.info
echo "restart terminal"
